DROP DATABASE IF EXISTS dega_spring_cars;

CREATE DATABASE dega_spring_cars;

\connect dega_spring_cars;

CREATE TABLE IF NOT EXISTS USERS
(
  USER_ID SERIAL PRIMARY KEY,
  NAME    TEXT
);

CREATE TABLE IF NOT EXISTS CAR_BRANDS
(
  CAR_BRAND_ID SERIAL PRIMARY KEY,
  NAME         TEXT
);

CREATE TABLE IF NOT EXISTS ADVERTISEMENTS
(
  ADVERTISEMENT_ID SERIAL PRIMARY KEY,
  DESCRIPTION      TEXT,
  CAR_BRAND_ID     INTEGER REFERENCES CAR_BRANDS (CAR_BRAND_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO CAR_BRANDS (NAME)
VALUES ('Audi'), ('BMW'), ('Chevrolet'), ('Ford');

INSERT INTO ADVERTISEMENTS (DESCRIPTION, CAR_BRAND_ID)
VALUES ('my 1 advert', 2),
  ('my 2 advert', 4),
  ('my 3 advert', 1);