DROP DATABASE IF EXISTS dega_servlets_html;

CREATE DATABASE dega_servlets_html;

\connect dega_servlets_html;

CREATE TABLE IF NOT EXISTS USERS
(ID SERIAL PRIMARY KEY,
LOGIN TEXT UNIQUE,
PASSWORD TEXT,
NAME CHARACTER(1000),
EMAIL CHARACTER(1000),
CREATEDATE TIMESTAMP,
ROLE TEXT);

INSERT INTO USERS (LOGIN, PASSWORD, NAME, EMAIL, CREATEDATE, ROLE)
VALUES ('root', 'root', 'root', 'root@root', '2016-01-01 00:00:00', 'ADMINISTRATOR');