CREATE DATABASE dega_servlets_html;

\connect dega_servlets_html;

CREATE TABLE IF NOT EXISTS USERS
(ID SERIAL PRIMARY KEY,
NAME CHARACTER(1000) NOT NULL,
LOGIN CHARACTER(1000) NOT NULL,
EMAIL CHARACTER(1000) NOT NULL,
CREATEDATE TIMESTAMP NOT NULL);