-- DROP DATABASE IF EXISTS dega_spring_boot;
-- CREATE DATABASE dega_spring_boot;
-- \connect dega_spring_boot;

CREATE TABLE IF NOT EXISTS ROLES
(
  ROLE_ID SERIAL PRIMARY KEY,
  NAME    TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS USERS
(
  USER_ID  SERIAL PRIMARY KEY,
  USERNAME TEXT,
  PASSWORD TEXT,
  ENABLED  BOOLEAN NOT NULL DEFAULT TRUE,
  ROLE_ID  INTEGER REFERENCES ROLES (ROLE_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CAR_BRANDS
(
  CAR_BRAND_ID SERIAL PRIMARY KEY,
  NAME         TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS CAR_MODELS
(
  CAR_MODEL_ID SERIAL PRIMARY KEY,
  NAME         TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS ADVERTISEMENTS
(
  ADVERTISEMENT_ID SERIAL PRIMARY KEY,
  DESCRIPTION      TEXT,
  CAR_BRAND_ID     INTEGER REFERENCES CAR_BRANDS (CAR_BRAND_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  CAR_MODEL_ID     INTEGER REFERENCES CAR_MODELS (CAR_MODEL_ID) ON UPDATE CASCADE ON DELETE CASCADE
);