DROP DATABASE IF EXISTS dega_spring_security;

CREATE DATABASE dega_spring_security;

\connect dega_spring_security;

CREATE TABLE IF NOT EXISTS ROLES
(
  ROLE_ID SERIAL PRIMARY KEY,
  NAME    TEXT
);

CREATE TABLE IF NOT EXISTS USERS
(
  USER_ID  SERIAL PRIMARY KEY,
  USERNAME TEXT,
  PASSWORD TEXT,
  ROLE_ID  INTEGER REFERENCES ROLES (ROLE_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CAR_BRANDS
(
  CAR_BRAND_ID SERIAL PRIMARY KEY,
  NAME         TEXT
);

CREATE TABLE IF NOT EXISTS CAR_MODELS
(
  CAR_MODEL_ID SERIAL PRIMARY KEY,
  NAME         TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS ADVERTISEMENTS
(
  ADVERTISEMENT_ID SERIAL PRIMARY KEY,
  DESCRIPTION      TEXT,
  CAR_BRAND_ID     INTEGER REFERENCES CAR_BRANDS (CAR_BRAND_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  CAR_MODEL_ID     INTEGER REFERENCES CAR_MODELS (CAR_MODEL_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO ROLES (NAME)
VALUES ('role_admin');

INSERT INTO USERS (USERNAME, PASSWORD, ROLE_ID)
VALUES ('admin', '123', 1);

INSERT INTO CAR_BRANDS (NAME)
VALUES ('Audi'), ('Nissan'), ('Kia'), ('Lada');

INSERT INTO CAR_MODELS (NAME)
VALUES ('A4'), ('A6'),
  ('Juke'), ('Qashqai'),
  ('Rio'), ('Sportage'),
  ('Granta'), ('Vesta');

INSERT INTO ADVERTISEMENTS (DESCRIPTION, CAR_BRAND_ID, CAR_MODEL_ID)
VALUES ('my 1 advert', 1, 2),
  ('my 2 advert', 2, 3),
  ('my 3 advert', 3, 5),
  ('my 4 advert', 4, 8);