DROP DATABASE IF EXISTS dega_servlets_final;

CREATE DATABASE dega_servlets_final;

\connect dega_servlets_final;

CREATE TABLE IF NOT EXISTS ROLES
(
  ID   SERIAL PRIMARY KEY,
  NAME TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS MUSIC_TYPE
(
  ID   SERIAL PRIMARY KEY,
  NAME TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS USERS
(
  ID         SERIAL PRIMARY KEY,
  LOGIN      TEXT UNIQUE,
  ROLE_ID    INTEGER REFERENCES ROLES (ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ADDRESS
(
  ID             SERIAL PRIMARY KEY,
  REPRESENTATION TEXT,
  USER_ID        INTEGER REFERENCES USERS (ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MUSICTYPE_USERS
(
  ID           SERIAL PRIMARY KEY,
  USER_ID      INTEGER REFERENCES USERS (ID) ON UPDATE CASCADE ON DELETE CASCADE,
  MUSICTYPE_ID INTEGER REFERENCES MUSIC_TYPE (ID) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO ROLES (NAME)
VALUES ('Administrator'), ('Moderator'), ('User');

INSERT INTO MUSIC_TYPE (NAME)
VALUES ('Rock'), ('Jazz'), ('Folk'), ('Metal'), ('Pop');

INSERT INTO USERS (LOGIN, ROLE_ID)
VALUES ('Ivanov', 1), ('Petrov', 2), ('Sidorov', 3);

INSERT INTO ADDRESS (REPRESENTATION, USER_ID)
VALUES ('Moscow, Lenina 1', 1);

INSERT INTO MUSICTYPE_USERS (USER_ID, MUSICTYPE_ID)
VALUES (1, 1), (1, 3);